#!/bin/bash

set -e

CONFIG_DIR=/etc/transmission
SETTINGS=$CONFIG_DIR/settings.json
TRANSMISSION=/usr/bin/transmission-daemon


ls -la $CONFIG_DIR

if [[ ! -f ${SETTINGS}.bak ]]; then
    if [ -z $TRANSMISSION_PASS ]; then
        echo Please provide a password for the 'transmission' user via the ADMIN_PASS enviroment variable.
        exit 1
    fi

    sed -i.bak -e "s/#TRANSMISSION_PASS#/$TRANSMISSION_PASS/" $SETTINGS 
fi

unset TRANSMISION_PASS

exec $TRANSMISSION -f --no-portmap --config-dir $CONFIG_DIR --log-info 
