#!/bin/bash

set -e

CONFIG_DIR=/etc/transmission
SETTINGS=$CONFIG_DIR/settings.json
TRANSMISSION=/usr/bin/transmission-daemon


ls -la $CONFIG_DIR
sed  -i -e "s/#TRANSMISSION_PASS#/$TRANSMISSION_PASS/" $SETTINGS
sed  -i -e "s/#TRANSMISSION_USER#/$TRANSMISSION_USER/" $SETTINGS 

unset TRANSMISION_PASS
unset TRANSMISION_USER
    

exec $TRANSMISSION -f --no-portmap --config-dir $CONFIG_DIR --log-info 
